apiVersion: v1
kind: Service
metadata:
  name: mysql-reader
  namespace: asiayo
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-reader
  clusterIP: None 

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-reader
  namespace: asiayo
spec:
  serviceName: mysql-reader
  replicas: 2
  selector:
    matchLabels:
      app: mysql-reader
  template:
    metadata:
      labels:
        app: mysql-reader
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        args:
        - "--read-only=1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234567890"  # prod要改使用secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi