apiVersion: v1
kind: Service
metadata:
  name: mysql-writer
  namespace: asiayo
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-writer
  clusterIP: None  

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-writer
  namespace: asiayo
spec:
  serviceName: mysql-writer
  replicas: 1
  selector:
    matchLabels:
      app: mysql-writer
  template:
    metadata:
      labels:
        app: mysql-writer
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234567890"  # prod 要改用secert
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi