apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: asiayo

patchesStrategicMerge:
- patch.yaml
- ingress-patch.yaml

commonLabels:
  environment: neil-test