apiVersion: v1
kind: PersistentVolume
metadata:
  name: asiayo-pv
  namespace: asiayo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: <ID> #如果有